# -*- coding: utf-8 -*-
"""export_onnx

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UwBTpxNX5olxgZL8GVKUq2XOPKqdvZAO
"""

from google.colab import files
files.download("/content/drive/MyDrive/affectnet_project/interview_best_model_v3.pth")

!pip install onnxscript -q

!pip install onnxruntime onnx -q
import onnx
import onnxruntime as ort
import numpy as np

# v3 모델 로드
v3_path = "/content/drive/MyDrive/affectnet_project/interview_best_model_v3.pth"
v3_ckpt = torch.load(v3_path, map_location='cpu')

model_export = models.mobilenet_v2(weights=None)
model_export.classifier = nn.Sequential(nn.Dropout(p=0.3), nn.Linear(model_export.last_channel, 3))
model_export.load_state_dict(v3_ckpt['model_state_dict'])

# FP32 캐스팅 (Mixed Precision 잔류 방지)
model_export = model_export.float().cpu()
model_export.eval()

# ONNX 변환
dummy = torch.randn(1, 3, 224, 224)
onnx_path = "/content/drive/MyDrive/affectnet_project/interview_model_v3.onnx"

torch.onnx.export(
    model_export, dummy, onnx_path,
    export_params=True,
    opset_version=13,
    do_constant_folding=True,
    input_names=['input'],
    output_names=['output'],
    dynamic_axes={'input': {0: 'batch_size'}, 'output': {0: 'batch_size'}}
)

# 검증
onnx_model = onnx.load(onnx_path)
onnx.checker.check_model(onnx_model)

with torch.no_grad():
    pt_out = model_export(dummy).numpy()
ort_out = ort.InferenceSession(onnx_path).run(None, {'input': dummy.numpy()})[0]
diff = np.abs(pt_out - ort_out).max()

size_mb = os.path.getsize(onnx_path) / (1024 * 1024)

print(f"\n📦 ONNX 변환 완료!")
print(f"   파일 크기: {size_mb:.1f} MB")
print(f"   PyTorch ↔ ONNX 최대 오차: {diff:.2e}")
if diff < 1e-4:
    print("   ✅ 검증 통과 — 파트너에게 안전하게 전달 가능!")
else:
    print("   ⚠️ 오차가 큽니다. 확인 필요.")

print(f"\n📋 v3 최종 성능:")
print(f"   Accuracy: {v3_ckpt['val_acc']:.4f}")
print(f"   Macro F1: {v3_ckpt['val_f1']:.4f}")