# -*- coding: utf-8 -*-
"""preprocess_opencv(affectnet dataset)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W9RhwXjHykon3rhb388ALqozvy6UEjK-
"""

# 1. 구글 드라이브 연결하기
from google.colab import drive
drive.mount('/content/drive')

import cv2
import glob
import os
from tqdm import tqdm

# 2. 경로 설정
raw_base = '/content/drive/MyDrive/affectnet_project/raw_data/archive (3)'
processed_base = '/content/drive/MyDrive/affectnet_project/processed_data'

# 3. OpenCV 얼굴 인식 모델 불러오기
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

def process_affectnet_cv2(mode):
    src_path = os.path.join(raw_base, mode)

    # 해당 폴더 안의 모든 이미지 경로 찾기
    image_paths = glob.glob(f'{src_path}/**/*.*', recursive=True)
    image_paths = [p for p in image_paths if p.lower().endswith(('.jpg', '.jpeg', '.png'))]

    print(f"\n--- {mode} 데이터 총 {len(image_paths)}장 처리를 시작합니다 ---")

    for img_path in tqdm(image_paths):
        # 감정 폴더 이름 추출 및 저장 경로 생성
        emotion = os.path.basename(os.path.dirname(img_path))
        save_dir = os.path.join(processed_base, mode.lower(), emotion.lower())
        os.makedirs(save_dir, exist_ok=True)

        # 이미지 읽기
        img = cv2.imread(img_path)
        if img is None: continue

        # OpenCV는 흑백 이미지에서 얼굴을 더 잘 찾습니다
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        # 얼굴 영역 탐지
        faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=4, minSize=(30, 30))

        if len(faces) > 0:
            # 여러 얼굴 중 첫 번째로 인식된 얼굴 하나만 선택
            (x, y, w, h) = faces[0]

            # 사진 범위를 벗어나지 않도록 좌표 보정 (에러 방지)
            x1, y1 = max(0, x), max(0, y)
            x2, y2 = min(img.shape[1], x + w), min(img.shape[0], y + h)

            # 얼굴 부분만 자르기 (Crop)
            cropped_face = img[y1:y2, x1:x2]
            if cropped_face.size == 0: continue

            # 224x224 사이즈로 리사이즈
            resized_face = cv2.resize(cropped_face, (224, 224))

            # 새로운 경로에 저장
            filename = os.path.basename(img_path)
            cv2.imwrite(os.path.join(save_dir, filename), resized_face)

# 4. Train과 Test 폴더 순차적 실행
process_affectnet_cv2('Train')
process_affectnet_cv2('Test')

print("\n🎉 [전처리 완료] 모든 이미지의 얼굴 자르기 작업이 끝났습니다!")