# -*- coding: utf-8 -*-
"""train_v3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XiuUncrfGvpjimk7rYCtH4tYjqistcKg
"""

import os
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from torchvision import models, transforms
from torch.utils.data import Dataset, DataLoader
from torch.amp import autocast, GradScaler
from PIL import Image
from sklearn.metrics import f1_score, accuracy_score, classification_report
from sklearn.utils.class_weight import compute_class_weight
from sklearn.model_selection import train_test_split
from collections import defaultdict
import pandas as pd

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"🔥 사용 장치: {DEVICE}")

IMG_SIZE = 224
BATCH_SIZE = 64
MERGED_DATA = "/content/drive/MyDrive/affectnet_project/merged_data"
CLASS_MAP = {'stable': 0, 'nervous': 1, 'neutral': 2}
CLASS_NAMES = ['Stable', 'Nervous', 'Neutral']

normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])

train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(10),
    transforms.RandomAffine(degrees=0, translate=(0.05, 0.05), scale=(0.9, 1.1)),
    transforms.ColorJitter(brightness=0.5, contrast=0.3, saturation=0.2),
    transforms.RandomGrayscale(p=0.05),
    transforms.GaussianBlur(kernel_size=3, sigma=(0.1, 1.5)),
    transforms.ToTensor(),
    normalize,
    transforms.RandomErasing(p=0.1, scale=(0.02, 0.1)),
])

val_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    normalize,
])


class MergedDataset(Dataset):
    def __init__(self, samples, transform):
        self.samples = samples
        self.transform = transform

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        path, label = self.samples[idx]
        try:
            image = Image.open(path).convert("RGB")
            image = self.transform(image)
            return image, label
        except:
            return torch.zeros(3, IMG_SIZE, IMG_SIZE), label


# 전체 데이터 로드
all_samples = []
for cls_name, cls_id in CLASS_MAP.items():
    cls_path = os.path.join(MERGED_DATA, 'train', cls_name)
    if not os.path.exists(cls_path):
        continue
    for f in os.listdir(cls_path):
        if f.lower().endswith(('.jpg', '.jpeg', '.png')):
            all_samples.append((os.path.join(cls_path, f), cls_id))

print(f"📂 전체 데이터: {len(all_samples)}장")

# 9:1로 train/val 분할
all_labels = [s[1] for s in all_samples]
train_samples, val_samples = train_test_split(
    all_samples, test_size=0.1, stratify=all_labels, random_state=42
)

print(f"📊 분할: Train {len(train_samples)}장 / Val {len(val_samples)}장")

train_dataset = MergedDataset(train_samples, train_transform)
val_dataset = MergedDataset(val_samples, val_transform)

# WeightedRandomSampler
train_labels = [s[1] for s in train_samples]
cw = compute_class_weight('balanced', classes=np.unique(train_labels), y=train_labels)
sw = [cw[l] for l in train_labels]
sampler = torch.utils.data.WeightedRandomSampler(sw, len(sw), replacement=True)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, sampler=sampler,
                          num_workers=4, pin_memory=True, persistent_workers=True, drop_last=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE,
                        num_workers=4, pin_memory=True, persistent_workers=True)

# v2 모델 로드
model = models.mobilenet_v2(weights=None)
model.classifier = nn.Sequential(nn.Dropout(p=0.3), nn.Linear(model.last_channel, 3))

checkpoint = torch.load(
    "/content/drive/MyDrive/affectnet_project/interview_best_model_v2.pth",
    map_location=DEVICE
)
model.load_state_dict(checkpoint['model_state_dict'])
model = model.to(DEVICE)

print(f"✅ v2 모델 로드 완료 (F1={checkpoint['val_f1']:.4f})")

V3_EPOCHS = 8
V3_LR = 5e-5

# 백본 뒤쪽만 해동
for p in model.features[:14].parameters():
    p.requires_grad = False
for p in model.features[14:].parameters():
    p.requires_grad = True
for p in model.classifier.parameters():
    p.requires_grad = True

optimizer = optim.AdamW([
    {'params': model.features[14:].parameters(), 'lr': V3_LR * 0.1},
    {'params': model.classifier.parameters(), 'lr': V3_LR},
], weight_decay=1e-4)

criterion = nn.CrossEntropyLoss()
scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='max', factor=0.5, patience=2)
scaler = GradScaler("cuda")

best_f1 = checkpoint['val_f1']
history = defaultdict(list)

print(f"\n🚀 v3 추가 학습 시작 (v2 Best F1: {best_f1:.4f})")
print("=" * 70)

for epoch in range(V3_EPOCHS):
    model.train()
    total_loss = 0
    for x, y in train_loader:
        x, y = x.to(DEVICE), y.to(DEVICE)
        optimizer.zero_grad()
        with autocast("cuda"):
            out = model(x)
            loss = criterion(out, y)
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()
        total_loss += loss.item()
    train_loss = total_loss / len(train_loader)

    model.eval()
    preds, labels = [], []
    with torch.no_grad():
        for x, y in val_loader:
            x, y = x.to(DEVICE), y.to(DEVICE)
            with autocast("cuda"):
                out = model(x)
            preds.extend(out.argmax(1).cpu().tolist())
            labels.extend(y.cpu().tolist())

    val_acc = accuracy_score(labels, preds)
    val_f1 = f1_score(labels, preds, average='macro')

    history['epoch'].append(epoch + 1)
    history['train_loss'].append(train_loss)
    history['val_acc'].append(val_acc)
    history['val_f1'].append(val_f1)
    pd.DataFrame(history).to_csv(
        "/content/drive/MyDrive/affectnet_project/v3_history.csv", index=False)

    scheduler.step(val_f1)

    status = ""
    if val_f1 > best_f1:
        best_f1 = val_f1
        torch.save({
            'epoch': epoch + 1,
            'model_state_dict': model.state_dict(),
            'val_f1': val_f1,
            'val_acc': val_acc,
            'config': {'num_classes': 3, 'class_names': CLASS_NAMES, 'img_size': IMG_SIZE}
        }, "/content/drive/MyDrive/affectnet_project/interview_best_model_v3.pth")
        status = " 🌟 Best!"

    print(f"[{epoch+1}/{V3_EPOCHS}] Loss={train_loss:.4f} | Acc={val_acc:.4f} | F1={val_f1:.4f}{status}")

print("=" * 70)
print(f"\n🎉 v3 완료! Best F1: {best_f1:.4f}")
print(f"\n📋 Classification Report:")
print(classification_report(labels, preds, target_names=CLASS_NAMES, digits=4))